basePath: /
definitions:
  api.ErrorResponse:
    properties:
      error:
        example: Houston, we have a problem!
        type: string
    type: object
  api.FileInfoResponse:
    items:
      $ref: '#/definitions/bittorrent.FileInfo'
    type: array
  api.MessageResponse:
    properties:
      message:
        example: done
        type: string
    type: object
  api.NewTorrentResponse:
    properties:
      info_hash:
        example: 000102030405060708090a0b0c0d0e0f10111213
        type: string
    type: object
  api.StatusResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
  api.TorrentInfoResponse:
    properties:
      info_hash:
        type: string
      status:
        $ref: '#/definitions/bittorrent.TorrentStatus'
        type: object
    type: object
  bittorrent.FileInfo:
    properties:
      id:
        type: integer
      length:
        type: integer
      name:
        type: string
      path:
        type: string
    type: object
  bittorrent.TorrentStatus:
    properties:
      active_time:
        type: integer
      all_time_download:
        type: integer
      all_time_upload:
        type: integer
      download_rate:
        type: integer
      finished_time:
        type: integer
      has_metadata:
        type: boolean
      name:
        type: string
      paused:
        type: boolean
      peers:
        type: integer
      peers_total:
        type: integer
      progress:
        type: number
      seeders:
        type: integer
      seeders_total:
        type: integer
      seeding_time:
        type: integer
      state:
        type: integer
      upload_rate:
        type: integer
    type: object
  settings.ProxySettings:
    properties:
      hostname:
        type: string
      password:
        type: string
      port:
        type: integer
      type:
        type: integer
      username:
        type: string
    type: object
  settings.Settings:
    properties:
      connections_limit:
        example: 0
        type: integer
      disable_dht:
        example: false
        type: boolean
      disable_upnp:
        example: false
        type: boolean
      download_path:
        example: downloads
        type: string
      encryption_policy:
        example: 0
        type: integer
      limit_after_buffering:
        example: false
        type: boolean
      listen_interfaces:
        type: string
      lower_listen_port:
        example: 6889
        type: integer
      max_download_rate:
        example: 0
        type: integer
      max_upload_rate:
        example: 0
        type: integer
      outgoing_interfaces:
        type: string
      proxy:
        $ref: '#/definitions/settings.ProxySettings'
        type: object
      seed_time_limit:
        example: 0
        type: integer
      seed_time_ratio_limit:
        example: 0
        type: integer
      session_save:
        example: 30
        type: integer
      share_ratio_limit:
        example: 0
        type: integer
      torrents_path:
        example: downloads/Torrents
        type: string
      tuned_storage:
        example: false
        type: boolean
      upper_listen_port:
        example: 7000
        type: integer
      user_agent:
        example: 0
        type: integer
    type: object
info:
  contact:
    email: i96751414@gmail.com
    name: i96751414
    url: https://github.com/i96751414/torrest
  description: Torrent server with a REST API.
  license:
    name: GPL3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html
  title: Torrest API
  version: "1.0"
paths:
  /add/magnet:
    get:
      description: add magnet to service
      operationId: add-magnet
      parameters:
      - description: magnet URI
        in: query
        name: uri
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.NewTorrentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Add Magnet
  /add/torrent:
    post:
      consumes:
      - multipart/form-data
      description: add torrent file to service
      operationId: add-torrent
      parameters:
      - description: torrent file
        in: formData
        name: torrent
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.NewTorrentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Add Torrent File
  /settings/get:
    get:
      description: get settings in JSON object
      operationId: get-settings
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/settings.Settings'
      summary: Get current settings
  /settings/set:
    post:
      consumes:
      - application/json
      description: set settings given the provided JSON object
      operationId: set-settings
      parameters:
      - description: Settings to be set
        in: body
        name: default
        schema:
          $ref: '#/definitions/settings.Settings'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/settings.Settings'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Set settings
  /shutdown:
    get:
      description: shutdown server
      operationId: shutdown
      responses:
        "200":
          description: OK
      summary: Shutdown
  /status:
    get:
      description: check server status
      operationId: status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StatusResponse'
      summary: Status
  /torrents:
    get:
      description: list all torrents from service
      operationId: list-torrents
      parameters:
      - description: get torrents status
        in: query
        name: status
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.TorrentInfoResponse'
            type: array
      summary: List Torrents
  /torrents/{infoHash}/files:
    get:
      description: get a list of the torrent files and its details
      operationId: torrent-files
      parameters:
      - description: torrent info hash
        in: path
        name: infoHash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.FileInfoResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get Torrent Files
  /torrents/{infoHash}/remove:
    get:
      description: remove torrent from service
      operationId: remove-torrent
      parameters:
      - description: torrent info hash
        in: path
        name: infoHash
        required: true
        type: string
      - description: delete files
        in: query
        name: delete
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Remove Torrent
  /torrents/{infoHash}/status:
    get:
      description: get torrent status
      operationId: torrent-status
      parameters:
      - description: torrent info hash
        in: path
        name: infoHash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bittorrent.TorrentStatus'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Get Torrent Status
swagger: "2.0"
